export const fields: { [key: string]: string[] } = {
  Protokoll: ['eigenes, eigenes, SMS', 'XMPP, IMAP(S),SMS, Matrix'],
  Android: ['JA', 'NEIN'],
  iOS: ['JA', 'NEIN'],
  Desktopversion: [
    'JA, (verschiedene XMPP-Clients), nur i.V.m. Smartphone',
    'NEIN',
  ],
  Freie_Software: ['JA', 'NEIN'],
  Kostenlos: ['JA', 'NEIN'],
  sync: ['JA', 'NEIN'],
  Backup: ['JA', 'NEIN'],
  selfhosting: ['JA', 'NEIN'],
  Kontaktliste_optional: [
    'JA',
    'NEIN, fuer Registrierung erforderlich, nein, teilt sie auch Facebook mit',
  ],
  Telefonnummer_optional: ['JA', 'NEIN'],
  Werbefrei: ['JA', 'NEIN'],
  Sprachnachrichten: ['JA', 'NEIN'],
  Audio_Videochats: ['JA', 'NEIN'],
  Gruppenchats: ['JA', 'NEIN'],
  Dateiaustausch: ['JA', 'NEIN'],
  e2e_Verschluesselung: ['JA', 'NEIN,optional'],
  Kontakten_Verifikation: ['JA', 'NEIN'],
  Tracker: ['JA', 'NEIN'],
  Sicherheitsaudit: [
    '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020',
    'n.v.',
  ],
};
export const names: { [key: string]: string } = {
  Protokoll: 'Eigenes Protokoll (JA) oder Offener Standard (Nein)?',
  Android: 'Fuer Android verfügbar?',
  iOS: 'Fuer iOS verfügbar?',
  Desktopversion: 'Ist ein WebClient / Desktopversion verfügbar?',
  Freie_Software: 'Freeware?',
  Kostenlos: 'Kostenlos?',
  sync: 'Mit mehreren Geraten nutzbar (Sync)',
  Backup: 'Kann Ich eigene Backups machen?',
  selfhosting: 'Kann Ich es selbst Hosten?',
  Kontaktliste_optional:
    'Kann ich es nutzen ohne meine Kontaktliste freigeben zu müssen?',
  Telefonnummer_optional:
    'Kann ich es nutzen ohne meine Telefonnummer angeben zu müssen?',
  Werbefrei: 'Keine Werbung?',
  Sprachnachrichten: 'Kann ich Sparchnichrichten senden / empfangen?',
  Audio_Videochats: 'Werden Video / Audiochats unterstützt?',
  Gruppenchats: 'Kann ich Gruppenchats auf nutzen?',
  Dateiaustausch: 'Kann ich Dateien senden?',
  e2e_Verschluesselung: 'Sind die Chats Ende zu Ende Verschlüsselt?',
  Kontakten_Verifikation: 'Können gesprächspartner Versifiziert werden?',
  Tracker: 'Ist ein Tracker eingebunden?',
  Sicherheitsaudit:
    'Wurde in den letzten 10 Jahren eine Sicherheits Audit durchgeführt?',
};
export const filter = {
  Protokoll: '',
  Android: '',
  iOS: '',
  Desktopversion: '',
  Freie_Software: '',
  Kostenlos: '',
  sync: '',
  Backup: '',
  selfhosting: '',
  Kontaktliste_optional: '',
  Telefonnummer_optional: '',
  Werbefrei: '',
  Sprachnachrichten: '',
  Audio_Videochats: '',
  Gruppenchats: '',
  Dateiaustausch: '',
  e2e_Verschluesselung: '',
  Kontakten_Verifikation: '',
  Tracker: '',
  Sicherheitsaudit: '',
};
export const data = [
  {
    name: 'WhatsApp',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'nur i.V.m. Smartphone',
    Freie_Software: 'NEIN',
    Kostenlos: 'JA',
    sync: 'NEIN',
    Backup: 'JA',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'NEIN',
    Telefonnummer_optional: 'nein, teilt sie auch Facebook mit',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'JA',
    Tracker: 'JA',
    Sicherheitsaudit: 'n.v.',
  },
  {
    name: 'Telegram',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'nur Client',
    Kostenlos: 'JA',
    sync: 'JA',
    Backup: 'manuell',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'fuer Registrierung erforderlich',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'optional',
    Kontakten_Verifikation: 'NEIN',
    Tracker: 'JA',
    Sicherheitsaudit: '2017',
  },
  {
    name: 'Signal',
    Protokoll: 'eigenes, SMS',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'JA',
    Kostenlos: 'JA',
    sync: 'JA',
    Backup: 'unter iOS nur teilweise',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'NEIN',
    Werbefrei: 'Eigenwerbung (abschaltbar)',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'JA',
    Tracker: 'NEIN',
    Sicherheitsaudit: '2016',
  },
  {
    name: 'Briar',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'NEIN',
    Desktopversion: 'NEIN',
    Freie_Software: 'JA',
    Kostenlos: 'JA',
    sync: 'NEIN',
    Backup: 'NEIN',
    selfhosting: 'nicht benoetigt',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'NEIN',
    Audio_Videochats: 'NEIN',
    Gruppenchats: 'JA',
    Dateiaustausch: 'nur Bilder',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'JA, notwendig',
    Tracker: 'NEIN',
    Sicherheitsaudit: '2017',
  },
  {
    name: 'Threema',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'nur i.V.m. Smartphone',
    Freie_Software: 'nur Client',
    Kostenlos: 'NEIN',
    sync: 'NEIN',
    Backup: 'ueberwiegend manuell',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'JA',
    Tracker: 'NEIN',
    Sicherheitsaudit: '2020',
  },
  {
    name: 'Delta Chat',
    Protokoll: 'IMAP(S)',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'JA',
    Kostenlos: 'JA',
    sync: 'manuell',
    Backup: 'manuell',
    selfhosting: 'JA',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'NEIN',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'nur Delta-Chat-Kontakte, opt.',
    Kontakten_Verifikation: 'JA',
    Tracker: 'Opt-in',
    Sicherheitsaudit: 'n.v.',
  },
  {
    name: 'Conversations',
    Protokoll: 'XMPP',
    Android: 'JA',
    iOS: 'NEIN',
    Desktopversion: 'JA (verschiedene XMPP-Clients)',
    Freie_Software: 'JA',
    Kostenlos: 'nicht ueber Play Store',
    sync: 'JA',
    Backup: 'manuell',
    selfhosting: 'JA',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'JA',
    Tracker: 'NEIN',
    Sicherheitsaudit: '2016',
  },
  {
    name: 'ChatSecure',
    Protokoll: 'XMPP',
    Android: 'NEIN',
    iOS: 'JA',
    Desktopversion: 'JA (verschiedene XMPP-Clients)',
    Freie_Software: 'JA',
    Kostenlos: 'JA',
    sync: 'JA',
    Backup: 'NEIN',
    selfhosting: 'JA',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'optional',
    Kontakten_Verifikation: 'JA',
    Tracker: 'unbekannt',
    Sicherheitsaudit: '2014',
  },
  {
    name: 'Wire',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'JA',
    Kostenlos: 'JA',
    sync: 'bis zu 8',
    Backup: 'manuell',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'JA',
    Tracker: 'NEIN',
    Sicherheitsaudit: '2018',
  },
  {
    name: 'iMessage',
    Protokoll: 'eigenes',
    Android: 'NEIN',
    iOS: 'JA',
    Desktopversion: 'nur macOS',
    Freie_Software: 'NEIN',
    Kostenlos: 'JA',
    sync: 'JA',
    Backup: 'JA',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'NEIN',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'separate App',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'NEIN',
    Tracker: 'NEIN',
    Sicherheitsaudit: '2016',
  },
  {
    name: 'Skype',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'NEIN',
    Kostenlos: 'JA',
    sync: 'JA',
    Backup: 'manuell',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'NEIN',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'kann behoerdl. umgangen werden',
    Kontakten_Verifikation: 'NEIN',
    Tracker: 'JA',
    Sicherheitsaudit: 'n.v.',
  },
  {
    name: 'Hike',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'NEIN',
    Freie_Software: 'NEIN',
    Kostenlos: 'JA',
    sync: 'NEIN',
    Backup: 'manuell',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'NEIN',
    Telefonnummer_optional: 'NEIN',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'NEIN',
    Kontakten_Verifikation: 'NEIN',
    Tracker: 'JA',
    Sicherheitsaudit: 'n.v.',
  },
  {
    name: 'Element',
    Protokoll: 'Matrix',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'JA',
    Kostenlos: 'JA',
    sync: 'JA',
    Backup: 'JA',
    selfhosting: 'JA',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'JA',
    Tracker: 'Opt-in',
    Sicherheitsaudit: '2016',
  },
  {
    name: 'Wickr',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'nur Client',
    Kostenlos: 'JA',
    sync: 'JA',
    Backup: 'NEIN',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'NEIN',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'teilweise',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'JA',
    Tracker: 'JA',
    Sicherheitsaudit: '2017',
  },
  {
    name: 'Jami',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'JA',
    Kostenlos: 'JA',
    sync: 'manuell',
    Backup: 'NEIN',
    selfhosting: 'nicht benoetigt',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'JA',
    Sprachnachrichten: 'NEIN',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'NEIN',
    e2e_Verschluesselung: 'JA',
    Kontakten_Verifikation: 'NEIN',
    Tracker: 'NEIN',
    Sicherheitsaudit: 'n.v.',
  },
  {
    name: 'ICQ',
    Protokoll: 'eigenes',
    Android: 'JA',
    iOS: 'JA',
    Desktopversion: 'JA',
    Freie_Software: 'NEIN',
    Kostenlos: 'JA',
    sync: 'JA',
    Backup: 'NEIN',
    selfhosting: 'NEIN',
    Kontaktliste_optional: 'JA',
    Telefonnummer_optional: 'JA',
    Werbefrei: 'NEIN',
    Sprachnachrichten: 'JA',
    Audio_Videochats: 'JA',
    Gruppenchats: 'JA',
    Dateiaustausch: 'JA',
    e2e_Verschluesselung: 'nur Videoanrufe',
    Kontakten_Verifikation: 'NEIN',
    Tracker: 'JA',
    Sicherheitsaudit: 'n.v.',
  },
];
